name: EasyCommands
version: ${project.version}
main: es.jaimetruman.Main
api-version: 1.16
authors: [ JaimeTruman ]
description: A effictive way to create commands and subcommands
commands:
  hola:
    description: mierda de comando
  bolsa:
    description: nada
  caca:
    description: adios
  adios:
    description: adios
